language: android
jdk: oraclejdk8
os:
  - linux
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
  - pip install codecov

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - ./gradlew check || ./gradlew check
  - ./gradlew assembleDebugAndroidTest
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest

after_success:
  - ./gradlew jacocoTestReport
  - codecov
